### ISSUE TITLE
Support for validators stake

### ISSUE THREAD

**Issue by rootulp** [helium/helium-ledger-app#39]
Does the helium-ledger-app support staking a validator? I don't see it on [these docs](https://docs.helium.com/wallets/ledger/) and was wondering if it would be supported prior to Helium validators launching on mainnet.

In other words, is this supported?
```
./helium-ledger-app validators stake 1YwLbGTCEhVbwKEehRVQRC8N3q35ydXTH1B6BQys5FB1paHssdR 10000 --commit
```
adapted from https://docs.helium.com/mine-hnt/validators/validator-deployment-guide/#stake-tokens-to-your-validator

**Comment by rootulp** [comment]
https://github.com/helium/helium-ledger-app/pull/34/files#diff-5affce66eb2896f497698c7b43cce24c09f29c350ff1fc5a1fe0406153fa6673R9-R15 makes me think this is supported and docs haven't been updated yet.

**Comment by abhay** [comment]
You're right. The code is ready but the ledger team hasn't finished their security review of version 2.1.1. Technically we're comfortable with the code that was added to the repo (since the core devs wrote it) but Ledger has a process around security review. 

https://github.com/LedgerHQ/app-helium/commit/d01c5fd514b332ec06c6814a5d0a65c8294a7fc0

Hoping this gets resolved soon.

**Comment by abhay** [comment]
docs coming: https://github.com/helium/docs/pull/380
